// <auto-generated />
using System;
using Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TestTaskContext))]
    partial class TestTaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Entities.BanksTotal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Bank")
                        .HasColumnType("integer")
                        .HasColumnName("bank");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("banks_total", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b928015-3861-413b-b8b1-4577007a0186"),
                            Bank = 0,
                            Total = 0m
                        },
                        new
                        {
                            Id = new Guid("44113f0f-0b46-4872-9791-4b4df718b82f"),
                            Bank = 1,
                            Total = 0m
                        },
                        new
                        {
                            Id = new Guid("02f2a68e-63d3-4f46-af7a-cae4b0fa0f9d"),
                            Bank = 2,
                            Total = 0m
                        },
                        new
                        {
                            Id = new Guid("33a67257-803f-4269-a5bb-002fc8d02bd7"),
                            Bank = 3,
                            Total = 0m
                        },
                        new
                        {
                            Id = new Guid("195ce1f6-5c92-4e6f-84db-04e8270b662a"),
                            Bank = 4,
                            Total = 0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
